---
title: "Prediction and Inference"
description: "the answer to why we would estimate f"
author: "Karl Marquez"
date: 2025-08-08
categories:
  - machine learning
  - r
  - statistics
format: 
  html: 
    code-fold: true
    code-summary: "Show me the code"
    code-overflow: wrap
    css: styles.css
execute: 
  warning: false
---

# Why estimate $f$? 
* Prediction
* Inference

## Prediction

From a previous post, the error term $\epsilon$ is a random error term that have approximately a mean of zero. In this setting, we can predict Y using $$
Y = \hat{f}(X)$$ where $\hat{f}$ is usually a black box - it's exact form isn't important if it gives accurate predictions for $Y$.

As an example, we use a patient's blood measurtements $X$ to predict their risk $Y$ of an adverse drug reaction, so we can avoid giving risky treatments.

The accuracy of $\hat{Y}$ as a prediction for $Y$ depends on

* Reducible error
  + Happens when $\hat{f}$ is not a perfect estimate of $f$
  + Can be reduced by using better statistical learning methods
* Irreducible error
  + Even with a perfect estimate $\hat{Y} = f(X)$ errors remain due to the random noise term $\epsilon$
  + May contain variables that affect $Y$ but are not recorded, so $f$ cannot use them
  + May include natural day-to-day variation in outcomes (e.g., patient's health status, drug manufacturing differences)

***The focus of statistical learning is on techniques for estimating $f$ to minimize the reducible error.*** 

## Inference

The goal of inference is not necessarily to make predictions for $Y$, but to understand the association between $Y$ and its predictors $X_1, \dots, X_p$. Therefore, we need to know the exact form of $\hat{f}$. 

Key questions in inference: 

* Identify important predictors: Only a small subset of variables may meaningfully affect $Y$. 
* Understand relationships: 
  + Direction (positive or negative association)
  + Possible interactions with other predictors 
* Model form: Determine if a simple linear model is sufficicent or if a more complex, nonlinear approach is needed.
  




















