project:
  type: website
  output-dir: docs

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this site and blog posts are under development - Karl M."
    type: secondary
    position: above-navbar
  title: "Residual Opinions"
  navbar:
    logo: images/nadine.jpg
    background: "#213555"
    foreground: "#f5efe7"
    search: true
    right:
      - text: "Posts"
        href: index.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    border: true
    background: "#213555"
    foreground: "#f5efe7"
    left: "Copyright 2025, Karl Marquez"
    right: 
      - icon: github
        href: https://github.com/istaloni
      - icon: linkedin
        href: https://www.linkedin.com/in/karl4marquez/
  cookie-consent:
    type: implied
    style: simple
    palette: light
        

format:
  html:
    linkcolor: "black"
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

editor: visual

