project:
  type: website
  output-dir: docs

website:
  title: "Steady Learning, SteadyGrit"
  navbar:
    logo: images/karlgolf.JPG
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    page-footer: "Made in Quarto"

format:
  html:
    linkcolor: "black"
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

