project:
  type: website
  output-dir: docs

website:
  title: "Residual Opinions"
  navbar:
    logo: images/nadine.jpg
    background: primary
    search: true
    right:
      - text: "Posts"
        href: index.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    border: true
    background: light
    left: "Copyright 2025, Karl Marquez"
    right: 
      - icon: github
        href: https://github.com/istaloni
      - icon: linkedin
        href: https://www.linkedin.com/in/karl4marquez/
        

format:
  html:
    linkcolor: "black"
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

editor: visual

