project:
  type: website
  output-dir: docs

website:
  title: "Steady Learning, SteadyGrit"
  navbar:
    logo: images/1-100.JPG
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

